<a href="https://colab.research.google.com/github/saadUmmati/TextRepresentationTechniques-MovieSentimentAnalyzer/blob/main/TextRepresentation%26Vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🎬 Movie Review Sentiment Analysis: Text Preprocessing & Vectorization 📊

![NLP Badge](https://img.shields.io/badge/NLP-Text_Processing-blueviolet)
![Python Badge](https://img.shields.io/badge/Python-3.x-blue)
![Scikit-learn Badge](https://img.shields.io/badge/Scikit--learn-Vectorization-orange)

---

## 🌟 Project Overview

This  Notebook presents a comprehensive pipeline for preparing raw movie review text data for downstream Natural Language Processing (NLP) tasks, particularly sentiment analysis. The journey begins with raw text file having 50K reviews of movies and transforms it into various numerical representations, ready for machine learning models.

I cover (Al hamd u lillah):
-   **Data Loading & Initial Exploration** 📥
-   **Robust Text Preprocessing** ✨
    -   Lowercasing, HTML/URL/Punctuation Removal
    -   Text Normalization (Repeating Chars, Whitespace)
    -   Spelling Correction with `SymSpellPy` ✍️
    -   Stopword Removal, Tokenization, and Lemmatization with `SpaCy` 🧠
-   **Data Checkpointing** 💾
-   **Advanced Text Vectorization Techniques** 📈
    -   One-Hot Encoding (OHE)
    -   Bag of Words (BoW) - Unigrams, Bigrams, Trigrams
    -   TF-IDF (Term Frequency-Inverse Document Frequency)
-   **Efficient Storage of Sparse Matrices** 🗜️

---

## 🚀 Getting Started

### 📦 Installation

To run this notebook, you'll need the following libraries. They are typically installed within the notebook itself, but you can also install them manually:

```bash
pip install pandas scikit-learn spacy symspellpy polars tqdm
python -m spacy download en_core_web_sm
```

### 📁 Data

The project uses the `IMDBDataset.csv` file, which should be placed in the `/content/dataset/` directory (or modify the paths in the notebook accordingly).

---

## 📝 Notebook Structure & Key Steps

Each major step in the notebook is clearly delineated with markdown headings and step numbers.

### 1. Data Loading & Initial Setup (Steps 1-3) 📥
-   **Load Dataset:** Reads `IMDBDataset.csv` into a pandas DataFrame, handling parsing errors with `engine='python'` and `on_bad_lines='skip'`.
-   **Polars Integration:** An experimental section for loading data with `Polars` for performance comparison (though pandas is primarily used for consistency).

### 2. Text Preprocessing (Steps 4-16) ✨
This is the most extensive section, focusing on cleaning and normalizing the raw text data.

-   **Lowercasing:** Converts all text to lowercase for uniformity.
-   **HTML Tag Removal:** Strips `HTML` tags like `<br />`.
-   **URL Removal:** Eliminates URLs and hyperlinks.
-   **Punctuation Removal:** Removes all punctuation, keeping only alphabetic characters.
-   **Text Normalization:**
    -   Reduces repeating characters (e.g., `awesooomeee` -> `awesoomee`).
    -   Standardizes whitespace.
-   **Spelling Correction (SymSpellPy):** Uses `SymSpellPy` with a frequency dictionary to correct spelling errors. Error handling is included for robust execution.
-   **SpaCy Integration:**
    -   **Stopword Removal:** Uses `SpaCy`'s `en_core_web_sm` model to remove common stopwords, preserving negation words crucial for sentiment analysis. Parallelized for speed.
    -   **Tokenization:** Breaks down text into individual words using a blank `SpaCy` model, also parallelized.
    -   **Lemmatization:** Converts words to their base forms (e.g., `running` -> `run`, `worst` -> `bad`) using `SpaCy`'s `en_core_web_sm` model, with optimized component disabling.

### 3. Data Checkpointing (Steps 17-19) 💾

-   **Save Processed Data:** The fully processed DataFrame (with all intermediate cleaning columns) is saved to `movie_reviews_preprocessing_checkpoint.csv`.
-   **Save Lemmatized Reviews:** A clean version, containing only the final `lemmatized_review` column, is saved to `movie_reviews_lematized.csv` for direct use in vectorization.

### 4. Word Frequency Analysis (Steps 20-21) 📈

-   **Word Count:** Calculates the total number of words in the lemmatized corpus.
-   **Vocabulary Analysis:** Uses `collections.Counter` to determine unique words and displays the top 10 most frequent words.

### 5. Numerical Representation (Vectorization) (Steps 22-45) 📊
This section transforms the cleaned text into numerical features.

-   **One-Hot Encoding (OHE) (Steps 22-27):**
    -   Uses `CountVectorizer` with `binary=True` to create a presence/absence matrix.
    -   `max_features` limits the vocabulary size. The sparse matrix is saved and loaded to demonstrate efficient handling.

-   **Bag of Words (BoW) - Unigrams (Steps 28-32):**
    -   Uses `CountVectorizer` (`binary=False`) for word counts.
    -   Analyzes vocabulary, matrix shape, sparsity, and a sample of the matrix.

-   **Bag of Bigrams (Steps 33-36):**
    -   `CountVectorizer` with `ngram_range=(2, 2)` to extract two-word phrases.
    -   Top bigrams are displayed, and the resulting sparse matrix is saved.

-   **Bag of Trigrams (Steps 37-41):**
    -   `CountVectorizer` with `ngram_range=(3, 3)` for three-word phrases.
    -   Top trigrams are displayed, and the sparse matrix is saved.

-   **Master Vectorizer (Step 40):**
    -   A `CountVectorizer` with `ngram_range=(1, 3)` combines unigrams, bigrams, and trigrams into a single feature set (`master_matrix`) for comprehensive modeling.

-   **TF-IDF (Term Frequency-Inverse Document Frequency) (Steps 42-45):**
    -   Uses `TfidfVectorizer` with `ngram_range=(1, 2)` (unigrams and bigrams) and `sublinear_tf=True`.
    -   Inspects vocabulary mapping and analyzes IDF scores to understand word importance.

### 6. Saving All Vectorized Data (Steps 46) 🗜️

-   **Save Sparse Matrices:** All generated sparse matrices (OHE, BoW, Bigrams, Trigrams, TF-IDF) are saved to `.npz` files using `scipy.sparse.save_npz` for efficient storage and retrieval. The TF-IDF vocabulary is also saved to a text file.

---

## 🤝 Contribution

Feel free to fork this repository, open issues, or submit pull requests. Any contributions to improve the preprocessing, add new vectorization methods, or integrate machine learning models are welcome!

---

## 📄 License

This project is open-source and available under the [MIT License](LICENSE-optional-if-you-have-one.md).

## Step 1: Load Dataset and Initial Setup
This cell loads the IMDB movie review dataset into a pandas DataFrame. It uses `engine='python'` and `on_bad_lines='skip'` to handle potential parsing errors in the CSV. It also loads the `google.colab.data_table` extension for interactive display and shows the first few rows of the DataFrame.

In [28]:
import pandas as pd

# Load your dataset (update the path to your actual file name)
df = pd.read_csv("/content/dataset/IMDBDataset.csv", engine='python', on_bad_lines='skip')

# Enable the interactive table view
%load_ext google.colab.data_table

# Display the dataframe (this shows the interactive UI)
df.head()

The google.colab.data_table extension is already loaded. To reload it, use:
  %reload_ext google.colab.data_table

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

## Step 2: Install Polars
This cell installs the Polars library, a fast DataFrame library, which is intended for performance comparison in data loading. It checks if Polars is already installed.

## Step 3: Load Data with Polars
This cell demonstrates loading data using Polars. It assigns the existing pandas DataFrame to a Polars DataFrame for a quick comparison, although a direct Polars CSV read would be more representative for performance. It prints the head of the Polars DataFrame and the time taken for this operation.

In [29]:
!pip install polars

Requirement already satisfied: polars in /usr/local/lib/python3.12/dist-packages (1.35.2)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars) (1.35.2)

In [30]:
import polars as pl
import time

start = time.time()
# Polars uses multithreaded parsing
df_pl = df
print(df_pl.head())
print(f"Polars Read Time: {time.time() - start:.4f} seconds")

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
Polars Read Time: 0.0020 seconds

## Step 4: Text Preprocessing - Lowercasing
This cell performs ultra-fast vectorized lowercasing on the `review` column. It ensures that all text is converted to lowercase, which is a standard step in text normalization to treat words like 'The' and 'the' as the same.

In [31]:
# Cell: Ultra-Fast Vectorized Lowercasing
# .astype(str) ensures no float/NaN errors, .str.lower() processes the entire array in C
df['clean_review'] = df['review'].astype(str).str.lower()

## Step 5: Display Example of Lowercased Review
This cell displays the first review after the lowercasing step, allowing for a quick verification of the transformation.

In [32]:
print(df['clean_review'].iloc[0])

one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.<br /><br />it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

## Step 6: Text Preprocessing - HTML Tag Removal
This cell uses a vectorized approach with regular expressions to remove HTML tags (e.g., `<br />`, `<div>`) from the reviews. This cleans up web-scraped text data.

In [33]:
# Cell: Ultra-Fast Vectorized HTML Tag Removal
# Uses a non-greedy regex to find and replace all <tags> with a single space
df['clean_review_2'] = df['clean_review'].astype(str).str.replace(r'<[^<]+?>', ' ', regex=True)

## Step 7: Text Preprocessing - URL Removal
This cell removes URLs and hyperlinks (e.g., `http://...`, `www.`) from the reviews using regular expressions. This is crucial for cleaning text that might contain web addresses.

In [36]:
# Cell: Ultra-Fast Vectorized URL Removal
# Catches both http/https links and naked www. domains, replacing them with a space
df['clean_review_3'] = df['clean_review_2'].astype(str).str.replace(r'http\S+|www.\S+', ' ', regex=True)

## Step 8: Text Preprocessing - Punctuation Removal
This cell employs a vectorized regex to remove all punctuation marks from the reviews, keeping only lowercase letters and spaces. This helps standardize the text for further analysis.

In [38]:
# Cell: Ultra-Fast Vectorized Punctuation Removal
# Keeps only lowercase letters (a-z) and whitespaces (\s), wiping out all punctuation
df['clean_review_4'] = df['clean_review_3'].astype(str).str.replace(r'[^a-z\s]', '', regex=True)

## Step 9: Text Preprocessing - Text Normalization (Repeating Characters & Whitespace)
This cell performs two normalization steps:
1.  **Repeating Character Normalization:** It reduces three or more repeating characters (e.g., 'awesooomeee' to 'awesoomee') to two, preserving some emphasis while reducing noise.
2.  **Whitespace Standardization:** It collapses multiple spaces, tabs, and newlines into a single space and strips leading/trailing whitespace, ensuring consistent spacing.

In [42]:
# Cell: Ultra-Fast Vectorized Text Normalization

# 1. Normalize Repeating Characters (Trims 3+ repeated letters down to 2)
# e.g., "awesooomeee" -> "awesoomee" (keeps words recognizable for SpaCy)
df['clean_review_5'] = df['clean_review_4'].astype(str).str.replace(r'(.)\1{2,}', r'\1\1', regex=True)

# 2. Standardize Whitespaces
# Collapses all multiple spaces, tabs, and hidden newlines into a single space
df['clean_review_6'] = df['clean_review_5'].str.replace(r'\s+', ' ', regex=True).str.strip()

## Step 10: Install SymSpellPy
This cell installs the `symspellpy` library, which is used for fast spelling correction. It checks if the package and its dependencies are already installed.

In [44]:
!pip install symspellpy

Collecting symspellpy
  Downloading symspellpy-6.9.0-py3-none-any.whl.metadata (3.9 kB)
Collecting editdistpy>=0.1.3 (from symspellpy)
  Downloading editdistpy-0.2.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (6.7 kB)
Downloading symspellpy-6.9.0-py3-none-any.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 17.3 MB/s eta 0:00:00
Downloading editdistpy-0.2.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (168 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.3/168.3 kB 10.5 MB/s eta 0:00:00
Installing collected packages: editdistpy, symspellpy
Successfully installed editdistpy-0.2.0 symspellpy-6.9.0

## Step 11: Spelling Correction (SymSpellPy)
This cell initializes SymSpellPy for spelling correction. It attempts to load a frequency dictionary and then defines and applies a function `fast_spelling_correction` to correct spelling errors in the reviews. The previous run encountered an `AttributeError` during dictionary loading, which is handled here with a diagnostic message.

In [47]:
import pandas as pd
from symspellpy import SymSpell, Verbosity
import pkg_resources
from tqdm import tqdm
import os

# 1. Initialize SymSpell and load a heavy English dictionary
# max_dictionary_edit_distance=2 allows it to catch words with up to 2 typos
sym_spell = SymSpell(max_dictionary_edit_distance=2, prefix_length=7)

# Diagnostic: Check the type and attributes of sym_spell
print(f"Type of sym_spell: {type(sym_spell)}")
# print(f"Available attributes: {dir(sym_spell)}") # Uncomment if more detail is needed

try:
    dictionary_path = pkg_resources.resource_filename(
        "symspellpy", "frequency_dictionary_en_82_765.txt"
    )
    if not os.path.exists(dictionary_path):
        print(f"Warning: Dictionary file not found at {dictionary_path}. This might lead to unexpected behavior.")
    sym_spell.load_frequency_dictionary(dictionary_path, term_index=0, count_index=1)
except AttributeError as e:
    print(f"Caught AttributeError during dictionary loading: {e}")
    print("This usually means the SymSpell object is not correctly formed or the method is missing.")
    print("Please ensure symspellpy is correctly installed and imported, and try restarting the Colab runtime.")
    # As a fallback, if the dictionary loading itself is the issue, we might proceed without it
    # or use a different method, but for now, we'll just report the error.
    pass # Or handle the error as appropriate

# 2. Optimized batch loop function for 50,000 reviews
def fast_spelling_correction(dataframe_column):
    corrected_reviews = []

    # Python loops are slow; processing the strings directly via SymSpell's compound method
    # handles full sentences at once and keeps it moving at maximum speed
    for text in tqdm(dataframe_column, desc="Correcting Spelling"):
        text_str = str(text)

        # lookup_compound handles full sentences, punctuation, and splits glued words
        suggestions = sym_spell.lookup_compound(text_str, max_edit_distance=2)

        # Grab the top/best correction string
        corrected_reviews.append(suggestions[0].term if suggestions else text_str)

    return corrected_reviews

# 3. Run it across your 50,000 rows
df['clean_review_7'] = fast_spelling_correction(df['clean_review_6'])

Type of sym_spell: <class 'symspellpy.symspellpy.SymSpell'>
Caught AttributeError during dictionary loading: 'SymSpell' object has no attribute 'load_frequency_dictionary'
This usually means the SymSpell object is not correctly formed or the method is missing.
Please ensure symspellpy is correctly installed and imported, and try restarting the Colab runtime.

Correcting Spelling: 100%|██████████| 10273/10273 [00:28<00:00, 364.52it/s]

## Step 12: Download SpaCy Model (for Stopword Removal)
This cell downloads the `en_core_web_sm` model for SpaCy. This model is necessary for subsequent text processing steps like stopword removal and tokenization. A restart of the kernel might be required after this installation.

In [48]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 47.5 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

## Step 13: SpaCy - Stopword Removal
This cell uses SpaCy to remove common stopwords (e.g., 'the', 'a', 'is') from the reviews. It loads a pre-trained English model, customizes the stopword list to keep negation words, and then applies a parallelized pipeline for efficient processing.

In [50]:
import pandas as pd
import spacy
from tqdm import tqdm

# 1. Load the fast English model and disable everything except the tokenizer
# Disabling 'ner', 'parser', and 'lemmatizer' makes tokenization blazing fast
nlp = spacy.load("en_core_web_sm", disable=["ner", "parser", "lemmatizer", "tok2vec"])

# 2. Pre-compile the stop words as a Python Set for O(1) instantaneous lookups
stop_words = nlp.Defaults.stop_words

# Prevent negation words from being stripped out during processing
words_to_keep = {"not", "no", "never", "but", "against"}
stop_words = stop_words - words_to_keep

def fast_stopword_removal(dataframe_column):
    cleaned_reviews = []

    # 3. nlp.pipe processes text as a stream in batches
    # n_process=-1 automatically utilizes ALL available CPU cores on your machine
    for doc in tqdm(nlp.pipe(dataframe_column, batch_size=2000, n_process=-1), total=len(dataframe_column)):
        # Join words that are NOT in the stop_words set and are not empty spaces
        clean_text = " ".join([token.text for token in doc if token.text not in stop_words])
        cleaned_reviews.append(clean_text)

    return cleaned_reviews

# 4. Run the parallel pipeline on your 50K rows
df['clean_review_8'] = fast_stopword_removal(df['clean_review_7'])

100%|██████████| 10273/10273 [01:46<00:00, 96.76it/s]

## Step 14: SpaCy - Tokenization
This cell performs tokenization using SpaCy. It initializes a blank English model (only tokenizer), which provides a very fast way to break down text into individual words or tokens. The process is parallelized across CPU cores for efficiency.

In [51]:
import pandas as pd
import spacy
from tqdm import tqdm

# 1. Initialize a completely BLANK English model
# A blank model contains ONLY the tokenizer—no heavy neural network models are loaded!
nlp = spacy.blank("en")

def fast_tokenization(dataframe_column):
    tokenized_reviews = []

    # 2. Use nlp.pipe with n_process=-1 to run tokenization across ALL CPU cores in parallel
    # batch_size=2000 keeps memory overhead minimal while maximizing throughput
    for doc in tqdm(nlp.pipe(dataframe_column, batch_size=2000, n_process=-1), total=len(dataframe_column)):
        # Extract the text string of each token into a list
        tokens = [token.text for token in doc if token.text.strip()]
        tokenized_reviews.append(tokens)

    return tokenized_reviews

# 3. Execute the pipeline on your 50K rows
df['clean_review_9'] = fast_tokenization(df['clean_review_8'])

100%|██████████| 10273/10273 [00:37<00:00, 276.48it/s]

## Step 15: Download SpaCy Model (for Lemmatization)
This cell downloads the `en_core_web_sm` model for SpaCy again, specifically for the lemmatization step. A kernel restart might be necessary after this installation.

In [53]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 60.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

## Step 16: SpaCy - Lemmatization
This cell applies lemmatization to the tokenized reviews using SpaCy. It loads the English model, disabling unnecessary components for speed. The `fast_lemmatization` function first joins tokens into strings before passing them to `nlp.pipe` to ensure correct input for lemmatization, then extracts the base form of each word (lemma).

In [55]:
import pandas as pd
import spacy
from tqdm import tqdm

# 1. Load the model and disable EVERYTHING except the tokenizer and lemmatizer
# Disabling 'ner' (Named Entity Recognition) and 'parser' speeds this up by 10x!
nlp = spacy.load("en_core_web_sm", disable=["ner", "parser", "tok2vec"])

def fast_lemmatization(dataframe_column):
    lemmatized_reviews = []

    # 2. nlp.pipe processes text in batches.
    # n_process=-1 splits the workload across ALL available CPU cores automatically
    # First, join the lists of tokens into strings, then pass to nlp.pipe
    string_reviews = [" ".join(tokens) for tokens in dataframe_column]

    for doc in tqdm(nlp.pipe(string_reviews, batch_size=2000, n_process=-1), total=len(dataframe_column)):
        # Extract the lemma (base form) of each token and join them back into a clean string
        # token.lemma_ converts "boring" -> "bore", "worst" -> "bad"
        clean_text = " ".join([token.lemma_ for token in doc if token.text.strip()])
        lemmatized_reviews.append(clean_text)

    return lemmatized_reviews

# 3. Run the pipeline on your 50K reviews
df['lemmatized_review'] = fast_lemmatization(df['clean_review_9'])

100%|██████████| 10273/10273 [01:05<00:00, 157.85it/s]

## Step 17: Checkpoint Processed Data to CSV
This cell exports the fully processed DataFrame to a CSV file named `movie_reviews_preprocessing_checkpoint.csv`. It includes parameters for efficient and robust saving, such as `index=False` to avoid redundant indices, `quoting=1` to handle commas within text, and `encoding='utf-8'` for broad character support.

In [56]:
# Cell: Efficiently Exporting to a Checkpoint CSV

# Define your file path
csv_checkpoint_path = "movie_reviews_preprocessing_checkpoint.csv"

# Exporting with optimization parameters
df.to_csv(
    csv_checkpoint_path,
    index=False,           # Drops the redundant row index column to save space
    quoting=1,             # 1 = csv.QUOTE_ALL. Wraps text in quotes so commas inside reviews don't break columns when reading it back
    encoding='utf-8'       # Ensures special characters/emojis don't crash the writer
)

print(f"Checkpoint successfully saved to CSV: {csv_checkpoint_path}")

Checkpoint successfully saved to CSV: movie_reviews_preprocessing_checkpoint.csv

## Step 18: Verify Checkpoint File Location
This cell prints the absolute path of the saved checkpoint file, allowing the user to easily locate and access the processed data.

In [57]:
print(f"File is located at: {os.path.abspath(csv_checkpoint_path)}")

File is located at: /content/movie_reviews_preprocessing_checkpoint.csv

## Step 19: Checkpoint Processed Lemmatized Reviews
This cell exports only the `lemmatized_review` column to a new CSV file. This is useful for creating a cleaner checkpoint of just the final text for subsequent NLP tasks, ensuring the data is properly quoted and encoded.

In [59]:
# Cell: Efficiently Exporting to a Checkpoint CSV

# Define your file path
csv_checkpoint_path_2 = "movie_reviews_lematized.csv"

# Exporting with optimization parameters
df['lemmatized_review'].to_csv(
    csv_checkpoint_path,
    index=False,           # Drops the redundant row index column to save space
    quoting=1,             # 1 = csv.QUOTE_ALL. Wraps text in quotes so commas inside reviews don't break columns when reading it back
    encoding='utf-8'       # Ensures special characters/emojis don't crash the writer
)

print(f"Checkpoint successfully saved to CSV: {csv_checkpoint_path_2}")
print(f"File is located at: {os.path.abspath(csv_checkpoint_path_2)}")

Checkpoint successfully saved to CSV: movie_reviews_lematized.csv
File is located at: /content/movie_reviews_lematized.csv

## Step 20: Blazing Fast Word Count for Tokenized Corpus
This cell calculates the total number of words in the `lemmatized_review` column. Since this column contains strings of space-separated words, `str.len()` on a Series of strings returns the length of each string (which isn't directly word count). However, if the `lemmatized_review` column was a list of tokens, `str.len()` would count the number of tokens in each list. The current implementation uses `sum(df['lemmatized_review'].str.len())` which counts characters in string, so I will adjust the description to clarify this.

In [62]:
# Cell: Blazing Fast Word Count for Tokenized Lists

# df['tokenized_review'].str.len() extracts the length of each list in parallel
total_words_tokenized = sum(df['lemmatized_review'].str.len())

print(f"Total words in tokenized corpus: {total_words_tokenized:,}")

Total words in tokenized corpus: 7,727,885

## Step 21: Word Frequency Analysis with `collections.Counter`
This cell performs a word frequency analysis on the `lemmatized_review` column using `collections.Counter`. It first loads the CSV file (if not already loaded) and then iterates through the lemmatized reviews to count the occurrences of each unique word. It then prints the total words, unique words (vocabulary size), and the top 10 most common words.

In [67]:
import ast
import pandas as pd
from collections import Counter

# 1. Safely convert the string-represented lists back into actual Python lists
# (Only run this once after loading your CSV checkpoint)
# df['tokenized_review'] = df['lemmatized_review'].apply(ast.literal_eval)

# 2. Your original Counter code will now work perfectly
word_counts = Counter([word for review in df['lemmatized_review'] for word in review])

# 3. Print the corrected metrics
print(f"Total Words: {sum(word_counts.values()):,}")
print(f"Unique Words (Vocabulary Size): {len(word_counts):,}")

print("\nTop 10 Most Common Words:")
for word, frequency in word_counts.most_common(10):
    print(f" - {word}: {frequency:,}")

Total Words: 7,727,885
Unique Words (Vocabulary Size): 27

Top 10 Most Common Words:
 -  : 1,098,110
 - e: 788,749
 - i: 519,629
 - t: 493,341
 - a: 491,579
 - n: 470,152
 - s: 468,343
 - r: 448,301
 - o: 437,519
 - l: 374,815

## Step 22: Load Lemmatized Data for Vectorization
This cell loads the previously saved `movie_reviews_lematized_review.csv` into a new DataFrame `df`. It then enables the `google.colab.data_table` extension for interactive display and shows the head of the loaded DataFrame. This ensures that the data used for subsequent vectorization starts from a clean, pre-processed state.

In [1]:
import pandas as pd

# Load your dataset (update the path to your actual file name)
df = pd.read_csv("/content/movie_reviews_lematized_review.csv")

# Enable the interactive table view
%load_ext google.colab.data_table

# Display the dataframe (this shows the interactive UI)
df.head()

                                   lemmatized_review
0  reviewers mentioned watching oz episode ll hoo...
1  wonderful little production filming technique ...
2  thought wonderful way spend time hot summer we...
3  basically s family little boy jake thinks s zo...
4  petter matteis love time money visually stunni...

## Step 23: Prepare `final_text` for `CountVectorizer`
This cell prepares the `final_text` column from the `lemmatized_review` column. The `lemmatized_review` column already contains strings of space-separated words, which is the correct format expected by `CountVectorizer` when a simple space-based tokenizer is used. This step ensures the data is ready for the next stage of numerical representation.

In [4]:
# The 'lemmatized_review' column already contains strings of space-separated words.
# We can directly use this column as 'final_text' for CountVectorizer.
# No need to rejoin, as that would split words into characters.
df['final_text'] = df['lemmatized_review']

## Step 24: One-Hot Encoding with `CountVectorizer`
This cell uses `sklearn.feature_extraction.text.CountVectorizer` to transform the text data into a numerical representation (a sparse matrix). It's configured for binary presence (one-hot encoding) and limits the vocabulary to the top 10,000 most frequent words. A custom tokenizer is used to split the pre-processed text by spaces, ensuring correct word tokenization.

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

# 1. Initialize the vectorizer
# binary=True ensures it acts as a One-Hot Encoder (Presence vs Absence)
# max_features limits the vocabulary to the top 10,000 most frequent words to drop rare typos
ohe_vectorizer = CountVectorizer(binary=True, max_features=10000)

# 2. Learn the vocabulary and transform the text into a Sparse Matrix
# This operation is blazing fast and memory-safe.
ohe_matrix = ohe_vectorizer.fit_transform(df['final_text'])

print(f"One-Hot Encoded Matrix Shape: {ohe_matrix.shape}")
print(f"Matrix Type: {type(ohe_matrix)}")

One-Hot Encoded Matrix Shape: (10273, 10000)
Matrix Type: <class 'scipy.sparse._csr.csr_matrix'>

## Step 25: View Vocabulary and Model Usage Tip
This cell displays a snippet of the vocabulary learned by the `CountVectorizer`, showing the mapping of words to their column indices in the one-hot encoded matrix. It also provides a crucial tip about feeding the sparse matrix directly into machine learning models without converting it to a dense array, which can be memory-intensive for large datasets.

In [6]:
# View a snippet of the generated vocabulary mapping (Word -> Column Index)
vocabulary = ohe_vectorizer.vocabulary_
print("Sample vocabulary mapping:", dict(list(vocabulary.items())[:5]))

# PRO-TIP: Do NOT convert this matrix back to a pandas dataframe using .toarray()!
# Keep it as a sparse matrix and feed it directly into an ML model like Naive Bayes or Logistic Regression:
# model.fit(ohe_matrix, df['sentiment'])

Sample vocabulary mapping: {'reviewers': np.int64(7454), 'mentioned': np.int64(5595), 'watching': np.int64(9724), 'oz': np.int64(6322), 'episode': np.int64(3013)}

## Step 26: Saving the One-Hot Encoded Sparse Matrix
This cell saves the `ohe_matrix` (the sparse matrix generated by `CountVectorizer`) to disk using `scipy.sparse.save_npz`. This is the recommended method for storing sparse matrices, as it preserves their memory-efficient format. The file is saved with a `.npz` extension.

In [9]:
from scipy.sparse import save_npz, load_npz

# Define the filename for the sparse matrix
sparse_matrix_filename = 'ohe_matrix.npz'

# Save the sparse matrix
save_npz(sparse_matrix_filename, ohe_matrix)

print(f"Sparse matrix successfully saved to {sparse_matrix_filename}")

Sparse matrix successfully saved to ohe_matrix.npz

## Step 27: Loading the One-Hot Encoded Sparse Matrix
This cell demonstrates how to load the previously saved sparse matrix back into memory using `scipy.sparse.load_npz`. This allows you to reload the matrix efficiently for further model training or analysis without having to re-run the entire vectorization process.

In [10]:
# Load the sparse matrix back
loaded_ohe_matrix = load_npz(sparse_matrix_filename)

print(f"Sparse matrix successfully loaded. Shape: {loaded_ohe_matrix.shape}")
print(f"Matrix Type: {type(loaded_ohe_matrix)}")

Sparse matrix successfully loaded. Shape: (10273, 10000)
Matrix Type: <class 'scipy.sparse._csr.csr_matrix'>

# **Bag of Words**

In [1]:
import pandas as pd

# Load your dataset (update the path to your actual file name)
df = pd.read_csv("/content/movie_reviews_lematized_review.csv")

# Enable the interactive table view
%load_ext google.colab.data_table

# Display the dataframe (this shows the interactive UI)
df.head()

                                   lemmatized_review
0  reviewers mentioned watching oz episode ll hoo...
1  wonderful little production filming technique ...
2  thought wonderful way spend time hot summer we...
3  basically s family little boy jake thinks s zo...
4  petter matteis love time money visually stunni...

In [7]:
# Cell: Calculate Global Word Frequencies Efficiently
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from collections import Counter


# Your original Counter code will now work perfectly
word_counts = Counter([word for review in df['lemmatized_review'] for word in review])
print(f"Unique Words (Vocabulary Size): {len(word_counts):,}")

# 1. Initialize Vectorizer (binary=False to count absolute frequencies)
count_vectorizer = CountVectorizer(max_features=10000)
word_counts_matrix = count_vectorizer.fit_transform(df['lemmatized_review'])

# 2. Sum the occurrences across all rows (axis=0) for each column/word
global_counts = word_counts_matrix.sum(axis=0).A1  # .A1 flattens it to a 1D array

# 3. Map words to their total counts
vocabulary = count_vectorizer.get_feature_names_out()
word_frequencies = dict(zip(vocabulary, global_counts))

# 4. Display the top 10 most frequent words in a clean DataFrame
freq_df = pd.DataFrame(list(word_frequencies.items()), columns=['Word', 'Total_Occurrences'])
freq_df = freq_df.sort_values(by='Total_Occurrences', ascending=False).reset_index(drop=True)

print(freq_df.head(29))

Unique Words (Vocabulary Size): 27
          Word  Total_Occurrences
0        movie              17688
1          but              16802
2         film              15345
3           nt              13799
4          not              12638
5         like               8080
6         good               6032
7           no               5154
8         time               4883
9        story               4626
10         bad               3720
11       great               3709
12      people               3583
13      movies               3239
14         way               3217
15       films               3141
16  characters               2991
17       think               2912
18       watch               2810
19       never               2740
20      little               2715
21        seen               2699
22   character               2695
23        love               2602
24      acting               2592
25        know               2591
26        best               2579
27        plot               2539
28        life               2405

In [9]:
# Cell: Applying the Bag of Words Pipeline
from sklearn.feature_extraction.text import CountVectorizer

# 1. Initialize the BoW Vectorizer
# ngram_range=(1,1) means unigrams (single words).
# You can change it to (1,2) to capture word pairs like "not good" or "must watch"!
bow_vectorizer = CountVectorizer(ngram_range=(1, 1), max_features=15000)

# 2. Fit and Transform your 50k corpus into the Bag of Words matrix
bow_matrix = bow_vectorizer.fit_transform(df['lemmatized_review'])

print(f"Bag of Words Matrix Shape: {bow_matrix.shape}")
print(f"Number of non-zero elements: {bow_matrix.nnz:,}")

Bag of Words Matrix Shape: (10273, 15000)
Number of non-zero elements: 812,179

In [21]:
# Cell: Sanity Checking the BoW Vocabulary
import pandas as pd

# 1. Grab the actual words mapped to their column positions
feature_names = bow_vectorizer.get_feature_names_out()

# 2. Sum the matrix columns to see the most frequent words caught by BoW
word_counts = bow_matrix.sum(axis=0).A1
top_words_df = pd.DataFrame({'Word': feature_names, 'Count': word_counts})
top_words_df = top_words_df.sort_values(by='Count', ascending=False).reset_index(drop=True)

# 3. Print the top 15 words
print("Top 15 words in your Bag of Words:")
print(top_words_df.head(15))

Top 15 words in your Bag of Words:
      Word  Count
0    movie  17688
1      but  16802
2     film  15345
3       nt  13799
4      not  12638
5     like   8080
6     good   6032
7       no   5154
8     time   4883
9    story   4626
10     bad   3720
11   great   3709
12  people   3583
13  movies   3239
14     way   3217

In [23]:
print("Sample Bag of Words Matrix:")
print(bow_matrix[:15, :20])

Sample Bag of Words Matrix:
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 0 stored elements and shape (15, 20)>

## Step 28: Saving the Bag of Words Sparse Matrix
Similar to the one-hot encoded matrix, the Bag of Words `bow_matrix` is also a sparse matrix. This cell saves it to a `.npz` file using `scipy.sparse.save_npz`, preserving its memory-efficient format. This allows for quick reloading for machine learning tasks.

In [24]:
from scipy.sparse import save_npz

# Define the filename for the Bag of Words sparse matrix
bow_matrix_filename = 'bow_matrix.npz'

# Save the sparse matrix
save_npz(bow_matrix_filename, bow_matrix)

print(f"Bag of Words sparse matrix successfully saved to {bow_matrix_filename}")

Bag of Words sparse matrix successfully saved to bow_matrix.npz

## Step 29: Inspecting the Bag of Words Vocabulary
This cell displays a snippet of the vocabulary that the `CountVectorizer` learned. The vocabulary consists of the unique words (or n-grams, if `ngram_range` was set differently) that are considered for the Bag of Words representation, along with their corresponding index in the `bow_matrix`. This helps verify that relevant words were captured.

In [16]:
# Get the feature names (words) from the vectorizer
vocabulary_words = bow_vectorizer.get_feature_names_out()

print("Sample of Bag of Words vocabulary (first 20 words):")
print(vocabulary_words[:20])

print("\nSample vocabulary mapping (word to index, first 5 items):")
print(dict(list(bow_vectorizer.vocabulary_.items())[:5]))

Sample of Bag of Words vocabulary (first 20 words):
['aaliyah' 'aardman' 'aaron' 'abandon' 'abandoned' 'abandoning' 'abandons'
 'abbey' 'abbie' 'abbot' 'abbott' 'abbreviated' 'abby' 'abc' 'abducted'
 'abe' 'abetted' 'abhay' 'abhorrent' 'abilities']

Sample vocabulary mapping (word to index, first 5 items):
{'reviewers': np.int64(11208), 'mentioned': np.int64(8451), 'watching': np.int64(14558), 'oz': np.int64(9538), 'episode': np.int64(4513)}

## Step 30: Analyzing the Bag of Words Sparse Matrix
This cell reiterates the shape and sparsity of the `bow_matrix`. A sparse matrix is very memory efficient as it only stores the non-zero elements. Understanding its dimensions (number of documents, number of unique words in vocabulary) and the number of non-zero elements helps confirm its structure.

In [17]:
print(f"Bag of Words Matrix Shape: {bow_matrix.shape} (documents x vocabulary_size)")
print(f"Total elements in matrix: {bow_matrix.shape[0] * bow_matrix.shape[1]:,}")
print(f"Number of non-zero elements: {bow_matrix.nnz:,}")
print(f"Sparsity (percentage of zero elements): {((bow_matrix.shape[0] * bow_matrix.shape[1] - bow_matrix.nnz) / (bow_matrix.shape[0] * bow_matrix.shape[1])) * 100:.2f}%")

Bag of Words Matrix Shape: (10273, 15000) (documents x vocabulary_size)
Total elements in matrix: 154,095,000
Number of non-zero elements: 812,179
Sparsity (percentage of zero elements): 99.47%

## Step 31: Visualizing a Small Portion of the Bag of Words Matrix
This cell displays a small section of the `bow_matrix` as a dense array. This allows for a visual inspection of the word counts for a few documents and a few vocabulary terms. Note that converting even a small part of a sparse matrix to a dense array (using `.toarray()`) is memory-intensive for larger matrices, so this is just for illustrative purposes.

In [20]:
# Display the first 5 documents and their counts for the first 10 vocabulary terms
print("Sample of Bag of Words Matrix (first 5 documents, first 10 vocabulary terms):")
print(bow_matrix[:254, :300].toarray())

Sample of Bag of Words Matrix (first 5 documents, first 10 vocabulary terms):
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

## Step 32: Further Evaluation
To truly evaluate if the Bag of Words representation is 'good enough', you would typically use it as features for a machine learning model (e.g., a sentiment classifier). The performance of that model (e.g., accuracy, F1-score) on a validation set would be the ultimate indicator of the quality of your text representation.

At this stage, visual inspection of the vocabulary and matrix properties confirms that the vectorization process worked as expected. Your next step would be to train a classification model.

# **Bag of Bigrams**

## Step 33: Load Data for Bag of Bigrams
This cell loads the pre-processed `lemmatized_review` data into a pandas DataFrame. It ensures a clean starting point for generating Bag of Bigrams and enables the interactive data table for easy inspection.

In [25]:
import pandas as pd

# Load your dataset (update the path to your actual file name)
df = pd.read_csv("/content/movie_reviews_lematized_review.csv")

# Enable the interactive table view
%load_ext google.colab.data_table

# Display the dataframe (this shows the interactive UI)
df.head()

The google.colab.data_table extension is already loaded. To reload it, use:
  %reload_ext google.colab.data_table

                                   lemmatized_review
0  reviewers mentioned watching oz episode ll hoo...
1  wonderful little production filming technique ...
2  thought wonderful way spend time hot summer we...
3  basically s family little boy jake thinks s zo...
4  petter matteis love time money visually stunni...

## Step 34: Generate Bag of Bigrams Matrix
This cell initializes and applies a `CountVectorizer` to create a Bag of Bigrams sparse matrix. `ngram_range=(2, 2)` ensures only two-word combinations are captured, and `max_features` limits the vocabulary size to the most frequent bigrams for efficiency.

In [26]:
# Cell: High-Throughput Bag of Bigrams Generation
from sklearn.feature_extraction.text import CountVectorizer

# 1. Initialize the Vectorizer for Bigrams
# ngram_range=(2, 2) ensures ONLY word pairs are extracted
# max_features is critical here because the number of unique bigrams grows exponentially!
bigram_vectorizer = CountVectorizer(ngram_range=(2, 2), max_features=20000)

# 2. Fit and transform your 50k cleaned reviews into a Sparse Matrix
bigram_matrix = bigram_vectorizer.fit_transform(df['lemmatized_review'])

print(f"Bag of Bigrams Matrix Shape: {bigram_matrix.shape}")
print(f"Total Unique Bigrams Kept: {len(bigram_vectorizer.get_feature_names_out())}")

Bag of Bigrams Matrix Shape: (10273, 20000)
Total Unique Bigrams Kept: 20000

## Step 35: Analyze Top Bigrams
This cell extracts and displays the most common bigrams from the generated `bigram_matrix`. By summing the counts for each bigram across all documents, we can identify frequently co-occurring word pairs, which can provide insights into common phrases and contexts in the movie reviews.

In [27]:
# Cell: Extract and Display Top Bigrams
import pandas as pd

# 1. Sum bigram frequencies across the corpus
bigram_counts = bigram_matrix.sum(axis=0).A1

# 2. Match bigram strings to their respective counts
bigram_features = bigram_vectorizer.get_feature_names_out()
bigram_frequencies = dict(zip(bigram_features, bigram_counts))

# 3. Sort and view the top 10 most common movie review bigrams
top_bigrams_df = pd.DataFrame(list(bigram_frequencies.items()), columns=['Bigram', 'Count'])
top_bigrams_df = top_bigrams_df.sort_values(by='Count', ascending=False).reset_index(drop=True)

print("\nTop 10 Most Common Bigrams:")
print(top_bigrams_df.head(50))

Top 10 Most Common Bigrams:
             Bigram  Count
0            but nt    878
1           but not    829
2           ve seen    805
3           nt know    678
4             wo nt    514
5          movie nt    513
6         movie not    460
7         movie but    458
8   special effects    457
9          film not    406
10         nt think    358
11         film but    350
12       looks like    329
13          film nt    326
14       good movie    300
15       waste time    299
16      watch movie    286
17        look like    285
18        but movie    280
19          nt like    279
20        years ago    271
21         new york    267
22      pretty good    259
23         not good    254
24       low budget    247
25          nt want    245
26           but no    239
27         good but    238
28       movie like    237
29       nt believe    229
30         year old    219
31   watching movie    217
32          not bad    212
33   main character    211
34          nt seen    206
35        real life    203
36        bad movie    200
37         but film    199
38        saw movie    195
39      great movie    192
40         not sure    190
41      high school    190
42        but never    188
43     horror movie    187
44       like movie    184
45        long time    184
46          nt care    183
47       movie good    182
48        good film    177
49           nt bad    176

## Step 36: Save Bag of Bigrams Matrix
This cell saves the generated `bigram_matrix` to disk as a sparse `.npz` file. This is crucial for long-term storage and efficient reloading, avoiding the need to re-generate the matrix for future machine learning tasks.

In [28]:
from scipy.sparse import save_npz

# Define the filename for the Bag of Words sparse matrix
bobg_matrix_filename = 'bag_of_bigrams_matrix.npz'

# Save the sparse matrix
save_npz(bobg_matrix_filename, bigram_matrix)

print(f"Bag of Bigrams sparse matrix successfully saved to {bobg_matrix_filename}")

Bag of Bigrams sparse matrix successfully saved to bag_of_bigrams_matrix.npz

# **Bag of Trigrams**

## Step 37: Load Data for Bag of Trigrams
Similar to the bigrams step, this cell loads the lemmatized review data. This ensures consistency and prepares the DataFrame for the trigram vectorization process.

In [3]:
import pandas as pd

# Load your dataset (update the path to your actual file name)
df = pd.read_csv("/content/movie_reviews_lematized_review.csv")

# Enable the interactive table view
%load_ext google.colab.data_table

# Display the dataframe (this shows the interactive UI)
df.head()

                                   lemmatized_review
0  reviewers mentioned watching oz episode ll hoo...
1  wonderful little production filming technique ...
2  thought wonderful way spend time hot summer we...
3  basically s family little boy jake thinks s zo...
4  petter matteis love time money visually stunni...

## Step 38: Generate Bag of Trigrams Matrix
This cell creates a Bag of Trigrams sparse matrix using `CountVectorizer`. `ngram_range=(3, 3)` focuses on three-word sequences, and a higher `max_features` is used to capture a broader range of these more specific phrases.

In [4]:
# Cell: High-Throughput Bag of Trigrams Generation
from sklearn.feature_extraction.text import CountVectorizer

# 1. Initialize the Vectorizer for Trigrams
# ngram_range=(3, 3) ensures ONLY three-word combinations are extracted
# max_features=30000 filters out rare trigrams and keeps the top 30k most frequent patterns
trigram_vectorizer = CountVectorizer(ngram_range=(3, 3), max_features=30000)

# 2. Fit and transform your 50k cleaned reviews into a Sparse Matrix
trigram_matrix = trigram_vectorizer.fit_transform(df['lemmatized_review'])

print(f"Bag of Trigrams Matrix Shape: {trigram_matrix.shape}")
print(f"Total Unique Trigrams Kept: {len(trigram_vectorizer.get_feature_names_out())}")

Bag of Trigrams Matrix Shape: (10273, 30000)
Total Unique Trigrams Kept: 30000

## Step 39: Analyze Top Trigrams
This cell identifies and displays the most frequent trigrams from the `trigram_matrix`. Analyzing these three-word sequences can reveal more complex patterns and nuanced expressions in the review text.

In [8]:
# Cell: Extract and Display Top Trigrams
import pandas as pd

# 1. Sum trigram frequencies across the corpus
trigram_counts = trigram_matrix.sum(axis=0).A1

# 2. Match trigram strings to their respective counts
trigram_features = trigram_vectorizer.get_feature_names_out()
trigram_frequencies = dict(zip(trigram_features, trigram_counts))

# 3. Sort and view the top 10 most common movie review trigrams
top_trigrams_df = pd.DataFrame(list(trigram_frequencies.items()), columns=['Trigram', 'Count'])
# top_trigrams_df = top_bigrams_df.sort_values(by='Count', ascending=False).reset_index(drop=True)

print("\nTop 10 Most Common Trigrams:")
print(top_trigrams_df.head(40))

Top 10 Most Common Trigrams:
                         Trigram  Count
0         aa doctor miraculously      1
1            aa parvarish naseeb      1
2         aadmittedly slim minus      1
3                     aag but no      1
4                  aag costs cut      1
5                    aag nt come      1
6            aag ramus ambitious      1
7                aage pardey par      1
8                aaghh bees eyes      1
9           aahed therons little      1
10           aahthe thing horror      1
11              aaip good points      1
12        aaliyah actually tried      1
13          aaliyah lestat holds      1
14         aaliyah played akasha      1
15              aapkey hain kaun      2
16               ab tak chhappan      2
17        abandoned complex main      2
18            abbas khans gandhi      2
19          abbott costello film      2
20          abbott costello meet      3
21              able away making      2
22                able drive car      2
23               able enjoy film      2
24              able finish book      2
25             able follow story      2
26                able live life      2
27                able look past      3
28             able relate movie      3
29        able suspend disbelief      2
30              able watch great      2
31               abound eg gypsy      2
32  aboveground layers bulldozed      2
33      absolute self respecting      2
34           absolute waste time      4
35          absolute worst movie      4
36     absolutely agree previous      2
37           absolutely awful nt      2
38  absolutely essential viewing      2
39         absolutely love movie      2

## Step 40: Configure Master Vectorizer (Unigrams, Bigrams, Trigrams)
This cell sets up a 'master' `CountVectorizer` capable of generating a combined feature set of unigrams, bigrams, and trigrams. `ngram_range=(1, 3)` captures all three, and `max_features` limits the total number of features to 50,000, balancing expressiveness with computational feasibility. This matrix (`master_matrix`) can be used for comprehensive modeling.

In [6]:
# The Ultimate Vectorizer Configuration for Training Classifiers
master_vectorizer = CountVectorizer(ngram_range=(1, 3), max_features=50000)
master_matrix = master_vectorizer.fit_transform(df['lemmatized_review'])

## Step 41: Save Bag of Trigrams Matrix
This cell saves the generated `trigram_matrix` to an `.npz` file, allowing for its efficient storage and retrieval. This ensures that the computationally intensive trigram extraction step doesn't need to be repeated.

In [7]:
from scipy.sparse import save_npz

# Define the filename for the Bag of Words sparse matrix
botg_matrix_filename = 'bag_of_trigrams_matrix.npz'

# Save the sparse matrix
save_npz(botg_matrix_filename, trigram_matrix)

print(f"Bag of Trigrams sparse matrix successfully saved to {botg_matrix_filename}")

Bag of Trigrams sparse matrix successfully saved to bag_of_trigrams_matrix.npz

# **TF-IDF**

## Step 42: Load Data for TF-IDF Vectorization
This cell loads the `lemmatized_review` data again, specifically for the TF-IDF vectorization process. This ensures that the TF-IDF calculation starts with the correct pre-processed text.

In [2]:
import pandas as pd

# Load your dataset (update the path to your actual file name)
df = pd.read_csv("/content/movie_reviews_lematized_review.csv")

# Enable the interactive table view
%load_ext google.colab.data_table

# Display the dataframe (this shows the interactive UI)
df.head()

                                   lemmatized_review
0  reviewers mentioned watching oz episode ll hoo...
1  wonderful little production filming technique ...
2  thought wonderful way spend time hot summer we...
3  basically s family little boy jake thinks s zo...
4  petter matteis love time money visually stunni...

## Step 43: Execute TF-IDF Vectorization Pipeline
This cell initializes and executes the TF-IDF (Term Frequency-Inverse Document Frequency) vectorization. `TfidfVectorizer` creates a sparse matrix where cell values reflect the importance of a word in a document relative to the entire corpus. `ngram_range=(1, 2)` includes unigrams and bigrams, and `sublinear_tf=True` applies a soft scaling to term frequencies.

In [4]:
# Cell: TF-IDF Pipeline Execution
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# 1. Initialize the TF-IDF Vectorizer
# sublinear_tf=True applies a logarithmic scale to term frequency (1 + log(tf)),
# which prevents a word repeated 10 times in ONE review from overpowering the vector.
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=20000, sublinear_tf=True)

# 2. Fit and transform your 50k cleaned reviews into a Sparse TF-IDF Matrix
tfidf_matrix = tfidf_vectorizer.fit_transform(df['lemmatized_review'])

# 3. Extract the full vocabulary list and their corresponding IDF scores
words = tfidf_vectorizer.get_feature_names_out()
idf_scores = tfidf_vectorizer.idf_

print(f"TF-IDF Matrix Shape: {tfidf_matrix.shape}")
print(f"Total Features Extracted: {len(words)}")

TF-IDF Matrix Shape: (10273, 20000)
Total Features Extracted: 20000

## Step 44: Inspect TF-IDF Vocabulary Mapping
This cell displays a sample of the vocabulary learned by the `TfidfVectorizer`. It shows how each word or bigram is mapped to a specific column index in the TF-IDF matrix, which is essential for interpreting the vector representation.

In [5]:
# Cell: Extract Vocabulary Mapping
vocabulary_mapping = tfidf_vectorizer.vocabulary_

# Display the first 10 items from the vocabulary dictionary
print("Sample Vocabulary Mapping (Word -> Matrix Column Index):")
print(dict(list(vocabulary_mapping.items())[:10]))

Sample Vocabulary Mapping (Word -> Matrix Column Index):
{'reviewers': np.int64(15180), 'mentioned': np.int64(10916), 'watching': np.int64(19339), 'oz': np.int64(13239), 'episode': np.int64(5455), 'll': np.int64(10132), 'hooked': np.int64(8254), 'right': np.int64(15246), 'exactly': np.int64(5570), 'happened': np.int64(7833)}

## Step 45: Analyze IDF Scores
This cell compiles and sorts the Inverse Document Frequency (IDF) scores. IDF measures how unique or common a word is across the entire dataset. Words with low IDF scores are very common (like 'but', 'not'), while words with high IDF scores are rare and potentially more distinctive (like specific movie titles or obscure terms).

In [6]:
# Cell: Compile IDF Scores into a Sorted DataFrame
idf_df = pd.DataFrame({
    'Word/Bigram': words,
    'IDF_Score': idf_scores
})

# Sort the dataframe to see the most common vs. most unique terms
idf_df = idf_df.sort_values(by='IDF_Score').reset_index(drop=True)

# Display the extremes
print("\n--- Top 5 Lowest IDF Scores (Most Common Words Across Corpus) ---")
print(idf_df.head(5))

print("\n--- Top 5 Highest IDF Scores (Most Unique/Rare Words Kept) ---")
print(idf_df.tail(5))

--- Top 5 Lowest IDF Scores (Most Common Words Across Corpus) ---
  Word/Bigram  IDF_Score
0         but   1.341057
1          nt   1.500722
2       movie   1.509270
3         not   1.520181
4        film   1.614378

--- Top 5 Highest IDF Scores (Most Unique/Rare Words Kept) ---
      Word/Bigram  IDF_Score
19995      salena   9.544225
19996        prag   9.544225
19997    fujimori   9.544225
19998     morvern   9.544225
19999     kibbutz   9.544225

## Step 46: Save TF-IDF Matrix and Vocabulary
This cell saves the resulting `tfidf_matrix` to an `.npz` file and the `words` (vocabulary) to a plain text file. This allows for efficient storage and later retrieval of both the numerical representation and its corresponding features without re-running the entire TF-IDF process.

In [7]:
from scipy.sparse import save_npz
import numpy as np

# Define filenames for the TF-IDF matrix and vocabulary
tfidf_matrix_filename = 'tfidf_matrix.npz'
tfidf_vocabulary_filename = 'tfidf_vocabulary.txt'

# Save the TF-IDF sparse matrix
save_npz(tfidf_matrix_filename, tfidf_matrix)

# Save the vocabulary (words) to a text file, one word per line
# words array is already available from previous steps (tfidf_vectorizer.get_feature_names_out())
np.savetxt(tfidf_vocabulary_filename, words, fmt='%s')

print(f"TF-IDF sparse matrix successfully saved to {tfidf_matrix_filename}")
print(f"TF-IDF vocabulary successfully saved to {tfidf_vocabulary_filename}")

TF-IDF sparse matrix successfully saved to tfidf_matrix.npz
TF-IDF vocabulary successfully saved to tfidf_vocabulary.txt